version: '3'
services:
    web:
        build: .
        ports:
            - "8000:80"
            - "3000:443"
        start: always
        depends_on:
            - mysqldb
    mysqldb:
        image: mysql:latest
        container_name: mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
        ports:
            - "8989:3306"